// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"sync"

	"github.com/lxc/incus/v7/client"
	"github.com/lxc/incus/v7/shared/api"

	api0 "github.com/FuturFusion/incus-redfish-proxy/internal/api"
)

// Ensure that IncusClientMock does implement api0.IncusClient.
// If this is not the case, regenerate this file with mockery.
var _ api0.IncusClient = &IncusClientMock{}

// IncusClientMock is a mock implementation of api0.IncusClient.
//
//	func TestSomethingThatUsesIncusClient(t *testing.T) {
//
//		// make and configure a mocked api0.IncusClient
//		mockedIncusClient := &IncusClientMock{
//			CreateStoragePoolVolumeFromISOFunc: func(pool string, args incus.StorageVolumeBackupArgs) (incus.Operation, error) {
//				panic("mock out the CreateStoragePoolVolumeFromISO method")
//			},
//			DeleteInstanceNVRAMGUIDVarFunc: func(name string, guid string, varName string) error {
//				panic("mock out the DeleteInstanceNVRAMGUIDVar method")
//			},
//			DeleteStoragePoolVolumeFunc: func(pool string, volType string, name string) error {
//				panic("mock out the DeleteStoragePoolVolume method")
//			},
//			GetInstanceFunc: func(name string) (*api.Instance, string, error) {
//				panic("mock out the GetInstance method")
//			},
//			GetInstanceNVRAMGUIDFunc: func(name string, guid string) (map[string]*api.InstanceNVRAMVariable, error) {
//				panic("mock out the GetInstanceNVRAMGUID method")
//			},
//			GetInstanceNVRAMGUIDVarFunc: func(name string, guid string, varName string) (*api.InstanceNVRAMVariable, string, error) {
//				panic("mock out the GetInstanceNVRAMGUIDVar method")
//			},
//			GetServerFunc: func() (*api.Server, string, error) {
//				panic("mock out the GetServer method")
//			},
//			HasExtensionFunc: func(extension string) bool {
//				panic("mock out the HasExtension method")
//			},
//			UpdateInstanceFunc: func(name string, instance api.InstancePut, ETag string) (incus.Operation, error) {
//				panic("mock out the UpdateInstance method")
//			},
//			UpdateInstanceNVRAMGUIDVarFunc: func(name string, guid string, varName string, data api.InstanceNVRAMVariablePut, ETag string) error {
//				panic("mock out the UpdateInstanceNVRAMGUIDVar method")
//			},
//			UpdateInstanceStateFunc: func(name string, state api.InstanceStatePut, ETag string) (incus.Operation, error) {
//				panic("mock out the UpdateInstanceState method")
//			},
//		}
//
//		// use mockedIncusClient in code that requires api0.IncusClient
//		// and then make assertions.
//
//	}
type IncusClientMock struct {
	// CreateStoragePoolVolumeFromISOFunc mocks the CreateStoragePoolVolumeFromISO method.
	CreateStoragePoolVolumeFromISOFunc func(pool string, args incus.StorageVolumeBackupArgs) (incus.Operation, error)

	// DeleteInstanceNVRAMGUIDVarFunc mocks the DeleteInstanceNVRAMGUIDVar method.
	DeleteInstanceNVRAMGUIDVarFunc func(name string, guid string, varName string) error

	// DeleteStoragePoolVolumeFunc mocks the DeleteStoragePoolVolume method.
	DeleteStoragePoolVolumeFunc func(pool string, volType string, name string) error

	// GetInstanceFunc mocks the GetInstance method.
	GetInstanceFunc func(name string) (*api.Instance, string, error)

	// GetInstanceNVRAMGUIDFunc mocks the GetInstanceNVRAMGUID method.
	GetInstanceNVRAMGUIDFunc func(name string, guid string) (map[string]*api.InstanceNVRAMVariable, error)

	// GetInstanceNVRAMGUIDVarFunc mocks the GetInstanceNVRAMGUIDVar method.
	GetInstanceNVRAMGUIDVarFunc func(name string, guid string, varName string) (*api.InstanceNVRAMVariable, string, error)

	// GetServerFunc mocks the GetServer method.
	GetServerFunc func() (*api.Server, string, error)

	// HasExtensionFunc mocks the HasExtension method.
	HasExtensionFunc func(extension string) bool

	// UpdateInstanceFunc mocks the UpdateInstance method.
	UpdateInstanceFunc func(name string, instance api.InstancePut, ETag string) (incus.Operation, error)

	// UpdateInstanceNVRAMGUIDVarFunc mocks the UpdateInstanceNVRAMGUIDVar method.
	UpdateInstanceNVRAMGUIDVarFunc func(name string, guid string, varName string, data api.InstanceNVRAMVariablePut, ETag string) error

	// UpdateInstanceStateFunc mocks the UpdateInstanceState method.
	UpdateInstanceStateFunc func(name string, state api.InstanceStatePut, ETag string) (incus.Operation, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateStoragePoolVolumeFromISO holds details about calls to the CreateStoragePoolVolumeFromISO method.
		CreateStoragePoolVolumeFromISO []struct {
			// Pool is the pool argument value.
			Pool string
			// Args is the args argument value.
			Args incus.StorageVolumeBackupArgs
		}
		// DeleteInstanceNVRAMGUIDVar holds details about calls to the DeleteInstanceNVRAMGUIDVar method.
		DeleteInstanceNVRAMGUIDVar []struct {
			// Name is the name argument value.
			Name string
			// GUID is the guid argument value.
			GUID string
			// VarName is the varName argument value.
			VarName string
		}
		// DeleteStoragePoolVolume holds details about calls to the DeleteStoragePoolVolume method.
		DeleteStoragePoolVolume []struct {
			// Pool is the pool argument value.
			Pool string
			// VolType is the volType argument value.
			VolType string
			// Name is the name argument value.
			Name string
		}
		// GetInstance holds details about calls to the GetInstance method.
		GetInstance []struct {
			// Name is the name argument value.
			Name string
		}
		// GetInstanceNVRAMGUID holds details about calls to the GetInstanceNVRAMGUID method.
		GetInstanceNVRAMGUID []struct {
			// Name is the name argument value.
			Name string
			// GUID is the guid argument value.
			GUID string
		}
		// GetInstanceNVRAMGUIDVar holds details about calls to the GetInstanceNVRAMGUIDVar method.
		GetInstanceNVRAMGUIDVar []struct {
			// Name is the name argument value.
			Name string
			// GUID is the guid argument value.
			GUID string
			// VarName is the varName argument value.
			VarName string
		}
		// GetServer holds details about calls to the GetServer method.
		GetServer []struct {
		}
		// HasExtension holds details about calls to the HasExtension method.
		HasExtension []struct {
			// Extension is the extension argument value.
			Extension string
		}
		// UpdateInstance holds details about calls to the UpdateInstance method.
		UpdateInstance []struct {
			// Name is the name argument value.
			Name string
			// Instance is the instance argument value.
			Instance api.InstancePut
			// ETag is the ETag argument value.
			ETag string
		}
		// UpdateInstanceNVRAMGUIDVar holds details about calls to the UpdateInstanceNVRAMGUIDVar method.
		UpdateInstanceNVRAMGUIDVar []struct {
			// Name is the name argument value.
			Name string
			// GUID is the guid argument value.
			GUID string
			// VarName is the varName argument value.
			VarName string
			// Data is the data argument value.
			Data api.InstanceNVRAMVariablePut
			// ETag is the ETag argument value.
			ETag string
		}
		// UpdateInstanceState holds details about calls to the UpdateInstanceState method.
		UpdateInstanceState []struct {
			// Name is the name argument value.
			Name string
			// State is the state argument value.
			State api.InstanceStatePut
			// ETag is the ETag argument value.
			ETag string
		}
	}
	lockCreateStoragePoolVolumeFromISO sync.RWMutex
	lockDeleteInstanceNVRAMGUIDVar     sync.RWMutex
	lockDeleteStoragePoolVolume        sync.RWMutex
	lockGetInstance                    sync.RWMutex
	lockGetInstanceNVRAMGUID           sync.RWMutex
	lockGetInstanceNVRAMGUIDVar        sync.RWMutex
	lockGetServer                      sync.RWMutex
	lockHasExtension                   sync.RWMutex
	lockUpdateInstance                 sync.RWMutex
	lockUpdateInstanceNVRAMGUIDVar     sync.RWMutex
	lockUpdateInstanceState            sync.RWMutex
}

// CreateStoragePoolVolumeFromISO calls CreateStoragePoolVolumeFromISOFunc.
func (mock *IncusClientMock) CreateStoragePoolVolumeFromISO(pool string, args incus.StorageVolumeBackupArgs) (incus.Operation, error) {
	if mock.CreateStoragePoolVolumeFromISOFunc == nil {
		panic("IncusClientMock.CreateStoragePoolVolumeFromISOFunc: method is nil but IncusClient.CreateStoragePoolVolumeFromISO was just called")
	}
	callInfo := struct {
		Pool string
		Args incus.StorageVolumeBackupArgs
	}{
		Pool: pool,
		Args: args,
	}
	mock.lockCreateStoragePoolVolumeFromISO.Lock()
	mock.calls.CreateStoragePoolVolumeFromISO = append(mock.calls.CreateStoragePoolVolumeFromISO, callInfo)
	mock.lockCreateStoragePoolVolumeFromISO.Unlock()
	return mock.CreateStoragePoolVolumeFromISOFunc(pool, args)
}

// CreateStoragePoolVolumeFromISOCalls gets all the calls that were made to CreateStoragePoolVolumeFromISO.
// Check the length with:
//
//	len(mockedIncusClient.CreateStoragePoolVolumeFromISOCalls())
func (mock *IncusClientMock) CreateStoragePoolVolumeFromISOCalls() []struct {
	Pool string
	Args incus.StorageVolumeBackupArgs
} {
	var calls []struct {
		Pool string
		Args incus.StorageVolumeBackupArgs
	}
	mock.lockCreateStoragePoolVolumeFromISO.RLock()
	calls = mock.calls.CreateStoragePoolVolumeFromISO
	mock.lockCreateStoragePoolVolumeFromISO.RUnlock()
	return calls
}

// DeleteInstanceNVRAMGUIDVar calls DeleteInstanceNVRAMGUIDVarFunc.
func (mock *IncusClientMock) DeleteInstanceNVRAMGUIDVar(name string, guid string, varName string) error {
	if mock.DeleteInstanceNVRAMGUIDVarFunc == nil {
		panic("IncusClientMock.DeleteInstanceNVRAMGUIDVarFunc: method is nil but IncusClient.DeleteInstanceNVRAMGUIDVar was just called")
	}
	callInfo := struct {
		Name    string
		GUID    string
		VarName string
	}{
		Name:    name,
		GUID:    guid,
		VarName: varName,
	}
	mock.lockDeleteInstanceNVRAMGUIDVar.Lock()
	mock.calls.DeleteInstanceNVRAMGUIDVar = append(mock.calls.DeleteInstanceNVRAMGUIDVar, callInfo)
	mock.lockDeleteInstanceNVRAMGUIDVar.Unlock()
	return mock.DeleteInstanceNVRAMGUIDVarFunc(name, guid, varName)
}

// DeleteInstanceNVRAMGUIDVarCalls gets all the calls that were made to DeleteInstanceNVRAMGUIDVar.
// Check the length with:
//
//	len(mockedIncusClient.DeleteInstanceNVRAMGUIDVarCalls())
func (mock *IncusClientMock) DeleteInstanceNVRAMGUIDVarCalls() []struct {
	Name    string
	GUID    string
	VarName string
} {
	var calls []struct {
		Name    string
		GUID    string
		VarName string
	}
	mock.lockDeleteInstanceNVRAMGUIDVar.RLock()
	calls = mock.calls.DeleteInstanceNVRAMGUIDVar
	mock.lockDeleteInstanceNVRAMGUIDVar.RUnlock()
	return calls
}

// DeleteStoragePoolVolume calls DeleteStoragePoolVolumeFunc.
func (mock *IncusClientMock) DeleteStoragePoolVolume(pool string, volType string, name string) error {
	if mock.DeleteStoragePoolVolumeFunc == nil {
		panic("IncusClientMock.DeleteStoragePoolVolumeFunc: method is nil but IncusClient.DeleteStoragePoolVolume was just called")
	}
	callInfo := struct {
		Pool    string
		VolType string
		Name    string
	}{
		Pool:    pool,
		VolType: volType,
		Name:    name,
	}
	mock.lockDeleteStoragePoolVolume.Lock()
	mock.calls.DeleteStoragePoolVolume = append(mock.calls.DeleteStoragePoolVolume, callInfo)
	mock.lockDeleteStoragePoolVolume.Unlock()
	return mock.DeleteStoragePoolVolumeFunc(pool, volType, name)
}

// DeleteStoragePoolVolumeCalls gets all the calls that were made to DeleteStoragePoolVolume.
// Check the length with:
//
//	len(mockedIncusClient.DeleteStoragePoolVolumeCalls())
func (mock *IncusClientMock) DeleteStoragePoolVolumeCalls() []struct {
	Pool    string
	VolType string
	Name    string
} {
	var calls []struct {
		Pool    string
		VolType string
		Name    string
	}
	mock.lockDeleteStoragePoolVolume.RLock()
	calls = mock.calls.DeleteStoragePoolVolume
	mock.lockDeleteStoragePoolVolume.RUnlock()
	return calls
}

// GetInstance calls GetInstanceFunc.
func (mock *IncusClientMock) GetInstance(name string) (*api.Instance, string, error) {
	if mock.GetInstanceFunc == nil {
		panic("IncusClientMock.GetInstanceFunc: method is nil but IncusClient.GetInstance was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockGetInstance.Lock()
	mock.calls.GetInstance = append(mock.calls.GetInstance, callInfo)
	mock.lockGetInstance.Unlock()
	return mock.GetInstanceFunc(name)
}

// GetInstanceCalls gets all the calls that were made to GetInstance.
// Check the length with:
//
//	len(mockedIncusClient.GetInstanceCalls())
func (mock *IncusClientMock) GetInstanceCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockGetInstance.RLock()
	calls = mock.calls.GetInstance
	mock.lockGetInstance.RUnlock()
	return calls
}

// GetInstanceNVRAMGUID calls GetInstanceNVRAMGUIDFunc.
func (mock *IncusClientMock) GetInstanceNVRAMGUID(name string, guid string) (map[string]*api.InstanceNVRAMVariable, error) {
	if mock.GetInstanceNVRAMGUIDFunc == nil {
		panic("IncusClientMock.GetInstanceNVRAMGUIDFunc: method is nil but IncusClient.GetInstanceNVRAMGUID was just called")
	}
	callInfo := struct {
		Name string
		GUID string
	}{
		Name: name,
		GUID: guid,
	}
	mock.lockGetInstanceNVRAMGUID.Lock()
	mock.calls.GetInstanceNVRAMGUID = append(mock.calls.GetInstanceNVRAMGUID, callInfo)
	mock.lockGetInstanceNVRAMGUID.Unlock()
	return mock.GetInstanceNVRAMGUIDFunc(name, guid)
}

// GetInstanceNVRAMGUIDCalls gets all the calls that were made to GetInstanceNVRAMGUID.
// Check the length with:
//
//	len(mockedIncusClient.GetInstanceNVRAMGUIDCalls())
func (mock *IncusClientMock) GetInstanceNVRAMGUIDCalls() []struct {
	Name string
	GUID string
} {
	var calls []struct {
		Name string
		GUID string
	}
	mock.lockGetInstanceNVRAMGUID.RLock()
	calls = mock.calls.GetInstanceNVRAMGUID
	mock.lockGetInstanceNVRAMGUID.RUnlock()
	return calls
}

// GetInstanceNVRAMGUIDVar calls GetInstanceNVRAMGUIDVarFunc.
func (mock *IncusClientMock) GetInstanceNVRAMGUIDVar(name string, guid string, varName string) (*api.InstanceNVRAMVariable, string, error) {
	if mock.GetInstanceNVRAMGUIDVarFunc == nil {
		panic("IncusClientMock.GetInstanceNVRAMGUIDVarFunc: method is nil but IncusClient.GetInstanceNVRAMGUIDVar was just called")
	}
	callInfo := struct {
		Name    string
		GUID    string
		VarName string
	}{
		Name:    name,
		GUID:    guid,
		VarName: varName,
	}
	mock.lockGetInstanceNVRAMGUIDVar.Lock()
	mock.calls.GetInstanceNVRAMGUIDVar = append(mock.calls.GetInstanceNVRAMGUIDVar, callInfo)
	mock.lockGetInstanceNVRAMGUIDVar.Unlock()
	return mock.GetInstanceNVRAMGUIDVarFunc(name, guid, varName)
}

// GetInstanceNVRAMGUIDVarCalls gets all the calls that were made to GetInstanceNVRAMGUIDVar.
// Check the length with:
//
//	len(mockedIncusClient.GetInstanceNVRAMGUIDVarCalls())
func (mock *IncusClientMock) GetInstanceNVRAMGUIDVarCalls() []struct {
	Name    string
	GUID    string
	VarName string
} {
	var calls []struct {
		Name    string
		GUID    string
		VarName string
	}
	mock.lockGetInstanceNVRAMGUIDVar.RLock()
	calls = mock.calls.GetInstanceNVRAMGUIDVar
	mock.lockGetInstanceNVRAMGUIDVar.RUnlock()
	return calls
}

// GetServer calls GetServerFunc.
func (mock *IncusClientMock) GetServer() (*api.Server, string, error) {
	if mock.GetServerFunc == nil {
		panic("IncusClientMock.GetServerFunc: method is nil but IncusClient.GetServer was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetServer.Lock()
	mock.calls.GetServer = append(mock.calls.GetServer, callInfo)
	mock.lockGetServer.Unlock()
	return mock.GetServerFunc()
}

// GetServerCalls gets all the calls that were made to GetServer.
// Check the length with:
//
//	len(mockedIncusClient.GetServerCalls())
func (mock *IncusClientMock) GetServerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetServer.RLock()
	calls = mock.calls.GetServer
	mock.lockGetServer.RUnlock()
	return calls
}

// HasExtension calls HasExtensionFunc.
func (mock *IncusClientMock) HasExtension(extension string) bool {
	if mock.HasExtensionFunc == nil {
		panic("IncusClientMock.HasExtensionFunc: method is nil but IncusClient.HasExtension was just called")
	}
	callInfo := struct {
		Extension string
	}{
		Extension: extension,
	}
	mock.lockHasExtension.Lock()
	mock.calls.HasExtension = append(mock.calls.HasExtension, callInfo)
	mock.lockHasExtension.Unlock()
	return mock.HasExtensionFunc(extension)
}

// HasExtensionCalls gets all the calls that were made to HasExtension.
// Check the length with:
//
//	len(mockedIncusClient.HasExtensionCalls())
func (mock *IncusClientMock) HasExtensionCalls() []struct {
	Extension string
} {
	var calls []struct {
		Extension string
	}
	mock.lockHasExtension.RLock()
	calls = mock.calls.HasExtension
	mock.lockHasExtension.RUnlock()
	return calls
}

// UpdateInstance calls UpdateInstanceFunc.
func (mock *IncusClientMock) UpdateInstance(name string, instance api.InstancePut, ETag string) (incus.Operation, error) {
	if mock.UpdateInstanceFunc == nil {
		panic("IncusClientMock.UpdateInstanceFunc: method is nil but IncusClient.UpdateInstance was just called")
	}
	callInfo := struct {
		Name     string
		Instance api.InstancePut
		ETag     string
	}{
		Name:     name,
		Instance: instance,
		ETag:     ETag,
	}
	mock.lockUpdateInstance.Lock()
	mock.calls.UpdateInstance = append(mock.calls.UpdateInstance, callInfo)
	mock.lockUpdateInstance.Unlock()
	return mock.UpdateInstanceFunc(name, instance, ETag)
}

// UpdateInstanceCalls gets all the calls that were made to UpdateInstance.
// Check the length with:
//
//	len(mockedIncusClient.UpdateInstanceCalls())
func (mock *IncusClientMock) UpdateInstanceCalls() []struct {
	Name     string
	Instance api.InstancePut
	ETag     string
} {
	var calls []struct {
		Name     string
		Instance api.InstancePut
		ETag     string
	}
	mock.lockUpdateInstance.RLock()
	calls = mock.calls.UpdateInstance
	mock.lockUpdateInstance.RUnlock()
	return calls
}

// UpdateInstanceNVRAMGUIDVar calls UpdateInstanceNVRAMGUIDVarFunc.
func (mock *IncusClientMock) UpdateInstanceNVRAMGUIDVar(name string, guid string, varName string, data api.InstanceNVRAMVariablePut, ETag string) error {
	if mock.UpdateInstanceNVRAMGUIDVarFunc == nil {
		panic("IncusClientMock.UpdateInstanceNVRAMGUIDVarFunc: method is nil but IncusClient.UpdateInstanceNVRAMGUIDVar was just called")
	}
	callInfo := struct {
		Name    string
		GUID    string
		VarName string
		Data    api.InstanceNVRAMVariablePut
		ETag    string
	}{
		Name:    name,
		GUID:    guid,
		VarName: varName,
		Data:    data,
		ETag:    ETag,
	}
	mock.lockUpdateInstanceNVRAMGUIDVar.Lock()
	mock.calls.UpdateInstanceNVRAMGUIDVar = append(mock.calls.UpdateInstanceNVRAMGUIDVar, callInfo)
	mock.lockUpdateInstanceNVRAMGUIDVar.Unlock()
	return mock.UpdateInstanceNVRAMGUIDVarFunc(name, guid, varName, data, ETag)
}

// UpdateInstanceNVRAMGUIDVarCalls gets all the calls that were made to UpdateInstanceNVRAMGUIDVar.
// Check the length with:
//
//	len(mockedIncusClient.UpdateInstanceNVRAMGUIDVarCalls())
func (mock *IncusClientMock) UpdateInstanceNVRAMGUIDVarCalls() []struct {
	Name    string
	GUID    string
	VarName string
	Data    api.InstanceNVRAMVariablePut
	ETag    string
} {
	var calls []struct {
		Name    string
		GUID    string
		VarName string
		Data    api.InstanceNVRAMVariablePut
		ETag    string
	}
	mock.lockUpdateInstanceNVRAMGUIDVar.RLock()
	calls = mock.calls.UpdateInstanceNVRAMGUIDVar
	mock.lockUpdateInstanceNVRAMGUIDVar.RUnlock()
	return calls
}

// UpdateInstanceState calls UpdateInstanceStateFunc.
func (mock *IncusClientMock) UpdateInstanceState(name string, state api.InstanceStatePut, ETag string) (incus.Operation, error) {
	if mock.UpdateInstanceStateFunc == nil {
		panic("IncusClientMock.UpdateInstanceStateFunc: method is nil but IncusClient.UpdateInstanceState was just called")
	}
	callInfo := struct {
		Name  string
		State api.InstanceStatePut
		ETag  string
	}{
		Name:  name,
		State: state,
		ETag:  ETag,
	}
	mock.lockUpdateInstanceState.Lock()
	mock.calls.UpdateInstanceState = append(mock.calls.UpdateInstanceState, callInfo)
	mock.lockUpdateInstanceState.Unlock()
	return mock.UpdateInstanceStateFunc(name, state, ETag)
}

// UpdateInstanceStateCalls gets all the calls that were made to UpdateInstanceState.
// Check the length with:
//
//	len(mockedIncusClient.UpdateInstanceStateCalls())
func (mock *IncusClientMock) UpdateInstanceStateCalls() []struct {
	Name  string
	State api.InstanceStatePut
	ETag  string
} {
	var calls []struct {
		Name  string
		State api.InstanceStatePut
		ETag  string
	}
	mock.lockUpdateInstanceState.RLock()
	calls = mock.calls.UpdateInstanceState
	mock.lockUpdateInstanceState.RUnlock()
	return calls
}
