// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"context"
	"sync"

	"github.com/gorilla/websocket"
	"github.com/lxc/incus/v6/client"
	"github.com/lxc/incus/v6/shared/api"

	api0 "github.com/FuturFusion/incus-redfish-proxy/internal/api"
)

// Ensure that IncusOperationMock does implement api0.IncusOperation.
// If this is not the case, regenerate this file with mockery.
var _ api0.IncusOperation = &IncusOperationMock{}

// IncusOperationMock is a mock implementation of api0.IncusOperation.
//
//	func TestSomethingThatUsesIncusOperation(t *testing.T) {
//
//		// make and configure a mocked api0.IncusOperation
//		mockedIncusOperation := &IncusOperationMock{
//			AddHandlerFunc: func(function func(api.Operation)) (*incus.EventTarget, error) {
//				panic("mock out the AddHandler method")
//			},
//			CancelFunc: func() error {
//				panic("mock out the Cancel method")
//			},
//			GetFunc: func() api.Operation {
//				panic("mock out the Get method")
//			},
//			GetWebsocketFunc: func(secret string) (*websocket.Conn, error) {
//				panic("mock out the GetWebsocket method")
//			},
//			RefreshFunc: func() error {
//				panic("mock out the Refresh method")
//			},
//			RemoveHandlerFunc: func(target *incus.EventTarget) error {
//				panic("mock out the RemoveHandler method")
//			},
//			WaitFunc: func() error {
//				panic("mock out the Wait method")
//			},
//			WaitContextFunc: func(ctx context.Context) error {
//				panic("mock out the WaitContext method")
//			},
//		}
//
//		// use mockedIncusOperation in code that requires api0.IncusOperation
//		// and then make assertions.
//
//	}
type IncusOperationMock struct {
	// AddHandlerFunc mocks the AddHandler method.
	AddHandlerFunc func(function func(api.Operation)) (*incus.EventTarget, error)

	// CancelFunc mocks the Cancel method.
	CancelFunc func() error

	// GetFunc mocks the Get method.
	GetFunc func() api.Operation

	// GetWebsocketFunc mocks the GetWebsocket method.
	GetWebsocketFunc func(secret string) (*websocket.Conn, error)

	// RefreshFunc mocks the Refresh method.
	RefreshFunc func() error

	// RemoveHandlerFunc mocks the RemoveHandler method.
	RemoveHandlerFunc func(target *incus.EventTarget) error

	// WaitFunc mocks the Wait method.
	WaitFunc func() error

	// WaitContextFunc mocks the WaitContext method.
	WaitContextFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// AddHandler holds details about calls to the AddHandler method.
		AddHandler []struct {
			// Function is the function argument value.
			Function func(api.Operation)
		}
		// Cancel holds details about calls to the Cancel method.
		Cancel []struct {
		}
		// Get holds details about calls to the Get method.
		Get []struct {
		}
		// GetWebsocket holds details about calls to the GetWebsocket method.
		GetWebsocket []struct {
			// Secret is the secret argument value.
			Secret string
		}
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
		}
		// RemoveHandler holds details about calls to the RemoveHandler method.
		RemoveHandler []struct {
			// Target is the target argument value.
			Target *incus.EventTarget
		}
		// Wait holds details about calls to the Wait method.
		Wait []struct {
		}
		// WaitContext holds details about calls to the WaitContext method.
		WaitContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockAddHandler    sync.RWMutex
	lockCancel        sync.RWMutex
	lockGet           sync.RWMutex
	lockGetWebsocket  sync.RWMutex
	lockRefresh       sync.RWMutex
	lockRemoveHandler sync.RWMutex
	lockWait          sync.RWMutex
	lockWaitContext   sync.RWMutex
}

// AddHandler calls AddHandlerFunc.
func (mock *IncusOperationMock) AddHandler(function func(api.Operation)) (*incus.EventTarget, error) {
	if mock.AddHandlerFunc == nil {
		panic("IncusOperationMock.AddHandlerFunc: method is nil but IncusOperation.AddHandler was just called")
	}
	callInfo := struct {
		Function func(api.Operation)
	}{
		Function: function,
	}
	mock.lockAddHandler.Lock()
	mock.calls.AddHandler = append(mock.calls.AddHandler, callInfo)
	mock.lockAddHandler.Unlock()
	return mock.AddHandlerFunc(function)
}

// AddHandlerCalls gets all the calls that were made to AddHandler.
// Check the length with:
//
//	len(mockedIncusOperation.AddHandlerCalls())
func (mock *IncusOperationMock) AddHandlerCalls() []struct {
	Function func(api.Operation)
} {
	var calls []struct {
		Function func(api.Operation)
	}
	mock.lockAddHandler.RLock()
	calls = mock.calls.AddHandler
	mock.lockAddHandler.RUnlock()
	return calls
}

// Cancel calls CancelFunc.
func (mock *IncusOperationMock) Cancel() error {
	if mock.CancelFunc == nil {
		panic("IncusOperationMock.CancelFunc: method is nil but IncusOperation.Cancel was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCancel.Lock()
	mock.calls.Cancel = append(mock.calls.Cancel, callInfo)
	mock.lockCancel.Unlock()
	return mock.CancelFunc()
}

// CancelCalls gets all the calls that were made to Cancel.
// Check the length with:
//
//	len(mockedIncusOperation.CancelCalls())
func (mock *IncusOperationMock) CancelCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCancel.RLock()
	calls = mock.calls.Cancel
	mock.lockCancel.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *IncusOperationMock) Get() api.Operation {
	if mock.GetFunc == nil {
		panic("IncusOperationMock.GetFunc: method is nil but IncusOperation.Get was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc()
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedIncusOperation.GetCalls())
func (mock *IncusOperationMock) GetCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetWebsocket calls GetWebsocketFunc.
func (mock *IncusOperationMock) GetWebsocket(secret string) (*websocket.Conn, error) {
	if mock.GetWebsocketFunc == nil {
		panic("IncusOperationMock.GetWebsocketFunc: method is nil but IncusOperation.GetWebsocket was just called")
	}
	callInfo := struct {
		Secret string
	}{
		Secret: secret,
	}
	mock.lockGetWebsocket.Lock()
	mock.calls.GetWebsocket = append(mock.calls.GetWebsocket, callInfo)
	mock.lockGetWebsocket.Unlock()
	return mock.GetWebsocketFunc(secret)
}

// GetWebsocketCalls gets all the calls that were made to GetWebsocket.
// Check the length with:
//
//	len(mockedIncusOperation.GetWebsocketCalls())
func (mock *IncusOperationMock) GetWebsocketCalls() []struct {
	Secret string
} {
	var calls []struct {
		Secret string
	}
	mock.lockGetWebsocket.RLock()
	calls = mock.calls.GetWebsocket
	mock.lockGetWebsocket.RUnlock()
	return calls
}

// Refresh calls RefreshFunc.
func (mock *IncusOperationMock) Refresh() error {
	if mock.RefreshFunc == nil {
		panic("IncusOperationMock.RefreshFunc: method is nil but IncusOperation.Refresh was just called")
	}
	callInfo := struct {
	}{}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc()
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedIncusOperation.RefreshCalls())
func (mock *IncusOperationMock) RefreshCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// RemoveHandler calls RemoveHandlerFunc.
func (mock *IncusOperationMock) RemoveHandler(target *incus.EventTarget) error {
	if mock.RemoveHandlerFunc == nil {
		panic("IncusOperationMock.RemoveHandlerFunc: method is nil but IncusOperation.RemoveHandler was just called")
	}
	callInfo := struct {
		Target *incus.EventTarget
	}{
		Target: target,
	}
	mock.lockRemoveHandler.Lock()
	mock.calls.RemoveHandler = append(mock.calls.RemoveHandler, callInfo)
	mock.lockRemoveHandler.Unlock()
	return mock.RemoveHandlerFunc(target)
}

// RemoveHandlerCalls gets all the calls that were made to RemoveHandler.
// Check the length with:
//
//	len(mockedIncusOperation.RemoveHandlerCalls())
func (mock *IncusOperationMock) RemoveHandlerCalls() []struct {
	Target *incus.EventTarget
} {
	var calls []struct {
		Target *incus.EventTarget
	}
	mock.lockRemoveHandler.RLock()
	calls = mock.calls.RemoveHandler
	mock.lockRemoveHandler.RUnlock()
	return calls
}

// Wait calls WaitFunc.
func (mock *IncusOperationMock) Wait() error {
	if mock.WaitFunc == nil {
		panic("IncusOperationMock.WaitFunc: method is nil but IncusOperation.Wait was just called")
	}
	callInfo := struct {
	}{}
	mock.lockWait.Lock()
	mock.calls.Wait = append(mock.calls.Wait, callInfo)
	mock.lockWait.Unlock()
	return mock.WaitFunc()
}

// WaitCalls gets all the calls that were made to Wait.
// Check the length with:
//
//	len(mockedIncusOperation.WaitCalls())
func (mock *IncusOperationMock) WaitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockWait.RLock()
	calls = mock.calls.Wait
	mock.lockWait.RUnlock()
	return calls
}

// WaitContext calls WaitContextFunc.
func (mock *IncusOperationMock) WaitContext(ctx context.Context) error {
	if mock.WaitContextFunc == nil {
		panic("IncusOperationMock.WaitContextFunc: method is nil but IncusOperation.WaitContext was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockWaitContext.Lock()
	mock.calls.WaitContext = append(mock.calls.WaitContext, callInfo)
	mock.lockWaitContext.Unlock()
	return mock.WaitContextFunc(ctx)
}

// WaitContextCalls gets all the calls that were made to WaitContext.
// Check the length with:
//
//	len(mockedIncusOperation.WaitContextCalls())
func (mock *IncusOperationMock) WaitContextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockWaitContext.RLock()
	calls = mock.calls.WaitContext
	mock.lockWaitContext.RUnlock()
	return calls
}
