// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mock

import (
	"sync"

	"github.com/lxc/incus/v6/client"
	"github.com/lxc/incus/v6/shared/api"

	api0 "github.com/FuturFusion/incus-redfish-proxy/internal/api"
)

// Ensure that IncusClientMock does implement api0.IncusClient.
// If this is not the case, regenerate this file with mockery.
var _ api0.IncusClient = &IncusClientMock{}

// IncusClientMock is a mock implementation of api0.IncusClient.
//
//	func TestSomethingThatUsesIncusClient(t *testing.T) {
//
//		// make and configure a mocked api0.IncusClient
//		mockedIncusClient := &IncusClientMock{
//			GetInstanceFunc: func(name string) (*api.Instance, string, error) {
//				panic("mock out the GetInstance method")
//			},
//			UpdateInstanceFunc: func(name string, instance api.InstancePut, ETag string) (incus.Operation, error) {
//				panic("mock out the UpdateInstance method")
//			},
//			UpdateInstanceStateFunc: func(name string, state api.InstanceStatePut, ETag string) (incus.Operation, error) {
//				panic("mock out the UpdateInstanceState method")
//			},
//		}
//
//		// use mockedIncusClient in code that requires api0.IncusClient
//		// and then make assertions.
//
//	}
type IncusClientMock struct {
	// GetInstanceFunc mocks the GetInstance method.
	GetInstanceFunc func(name string) (*api.Instance, string, error)

	// UpdateInstanceFunc mocks the UpdateInstance method.
	UpdateInstanceFunc func(name string, instance api.InstancePut, ETag string) (incus.Operation, error)

	// UpdateInstanceStateFunc mocks the UpdateInstanceState method.
	UpdateInstanceStateFunc func(name string, state api.InstanceStatePut, ETag string) (incus.Operation, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetInstance holds details about calls to the GetInstance method.
		GetInstance []struct {
			// Name is the name argument value.
			Name string
		}
		// UpdateInstance holds details about calls to the UpdateInstance method.
		UpdateInstance []struct {
			// Name is the name argument value.
			Name string
			// Instance is the instance argument value.
			Instance api.InstancePut
			// ETag is the ETag argument value.
			ETag string
		}
		// UpdateInstanceState holds details about calls to the UpdateInstanceState method.
		UpdateInstanceState []struct {
			// Name is the name argument value.
			Name string
			// State is the state argument value.
			State api.InstanceStatePut
			// ETag is the ETag argument value.
			ETag string
		}
	}
	lockGetInstance         sync.RWMutex
	lockUpdateInstance      sync.RWMutex
	lockUpdateInstanceState sync.RWMutex
}

// GetInstance calls GetInstanceFunc.
func (mock *IncusClientMock) GetInstance(name string) (*api.Instance, string, error) {
	if mock.GetInstanceFunc == nil {
		panic("IncusClientMock.GetInstanceFunc: method is nil but IncusClient.GetInstance was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockGetInstance.Lock()
	mock.calls.GetInstance = append(mock.calls.GetInstance, callInfo)
	mock.lockGetInstance.Unlock()
	return mock.GetInstanceFunc(name)
}

// GetInstanceCalls gets all the calls that were made to GetInstance.
// Check the length with:
//
//	len(mockedIncusClient.GetInstanceCalls())
func (mock *IncusClientMock) GetInstanceCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockGetInstance.RLock()
	calls = mock.calls.GetInstance
	mock.lockGetInstance.RUnlock()
	return calls
}

// UpdateInstance calls UpdateInstanceFunc.
func (mock *IncusClientMock) UpdateInstance(name string, instance api.InstancePut, ETag string) (incus.Operation, error) {
	if mock.UpdateInstanceFunc == nil {
		panic("IncusClientMock.UpdateInstanceFunc: method is nil but IncusClient.UpdateInstance was just called")
	}
	callInfo := struct {
		Name     string
		Instance api.InstancePut
		ETag     string
	}{
		Name:     name,
		Instance: instance,
		ETag:     ETag,
	}
	mock.lockUpdateInstance.Lock()
	mock.calls.UpdateInstance = append(mock.calls.UpdateInstance, callInfo)
	mock.lockUpdateInstance.Unlock()
	return mock.UpdateInstanceFunc(name, instance, ETag)
}

// UpdateInstanceCalls gets all the calls that were made to UpdateInstance.
// Check the length with:
//
//	len(mockedIncusClient.UpdateInstanceCalls())
func (mock *IncusClientMock) UpdateInstanceCalls() []struct {
	Name     string
	Instance api.InstancePut
	ETag     string
} {
	var calls []struct {
		Name     string
		Instance api.InstancePut
		ETag     string
	}
	mock.lockUpdateInstance.RLock()
	calls = mock.calls.UpdateInstance
	mock.lockUpdateInstance.RUnlock()
	return calls
}

// UpdateInstanceState calls UpdateInstanceStateFunc.
func (mock *IncusClientMock) UpdateInstanceState(name string, state api.InstanceStatePut, ETag string) (incus.Operation, error) {
	if mock.UpdateInstanceStateFunc == nil {
		panic("IncusClientMock.UpdateInstanceStateFunc: method is nil but IncusClient.UpdateInstanceState was just called")
	}
	callInfo := struct {
		Name  string
		State api.InstanceStatePut
		ETag  string
	}{
		Name:  name,
		State: state,
		ETag:  ETag,
	}
	mock.lockUpdateInstanceState.Lock()
	mock.calls.UpdateInstanceState = append(mock.calls.UpdateInstanceState, callInfo)
	mock.lockUpdateInstanceState.Unlock()
	return mock.UpdateInstanceStateFunc(name, state, ETag)
}

// UpdateInstanceStateCalls gets all the calls that were made to UpdateInstanceState.
// Check the length with:
//
//	len(mockedIncusClient.UpdateInstanceStateCalls())
func (mock *IncusClientMock) UpdateInstanceStateCalls() []struct {
	Name  string
	State api.InstanceStatePut
	ETag  string
} {
	var calls []struct {
		Name  string
		State api.InstanceStatePut
		ETag  string
	}
	mock.lockUpdateInstanceState.RLock()
	calls = mock.calls.UpdateInstanceState
	mock.lockUpdateInstanceState.RUnlock()
	return calls
}
